### ISSUE TITLE
Error no KongIngress "do-not-preserve-host"

### ISSUE THREAD

**Issue by ianmateusES** [devfullcycle/FC3-kong-automation#6]
Seguindo as aulas do módulo "API Gateway com Kong e Kubernetes", ao aplicar a configuração no Kubernetes usando o seguinte comando:

```sh
kubectl apply -f infra/kong-k8s/misc/apis/king.yaml -n bets
```

Encontrei o seguinte erro:

> O KongIngress "do-not-preserve-host" é inválido: <nil>: Valor inválido: "object": o campo 'route' não é mais suportado, utilize as anotações do Ingress em seu lugar.

Como solução, o Copilot sugeriu a seguinte correção:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: do-not-preserve-host
  annotations:
    configuration.konghq.com/preserve-host: "false"
upstream:
  host_header: bets.bets.svc
```

**Esta configuração resolveu o problema.**
